# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'Arriyadiyah' do
	project 'Arriyadiyah.xcodeproj'
	pod 'Firebase/Messaging', '~> 7.4.0'
end
